### ISSUE TITLE
Add warning about deleting existing data

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-fake-data-shopaholic-plugin#14]
There's no warning regarding deleting existing data while generating demo data. It should be.

![image](https://user-images.githubusercontent.com/196445/86166015-cc57b580-bb1c-11ea-8496-1ea3496e7ab4.png)
![image](https://user-images.githubusercontent.com/196445/86166056-da0d3b00-bb1c-11ea-9fd6-1c1c11a3a587.png)

We should warn user about it.

Which text formatting options are available in a popup? Is it possible to use [Callout](https://octobercms.com/docs/ui/callout)?

![image](https://user-images.githubusercontent.com/196445/86166722-e8a82200-bb1d-11ea-85c4-eb6de70e19e9.png)

**Comment by wobqqq** [comment]
45m

**Comment by lautsevich** [comment]
So, change the text on these popups to `This action will delete all existing data. Proceed?`

**Comment by lautsevich** [comment]
Done.
