### ISSUE TITLE
Error: A node cannot be moved to a descendant of itself

### ISSUE THREAD

**Issue by SebastiaanKloos** [oc-shopaholic/oc-fake-data-shopaholic-plugin#18]
When saving a generated category the error "A node cannot be moved to a descendant of itself" shows up. It can be fixed by changing the value of parent_id to null instead of 0. 

Don't have the time right now to correct this in the plugin. Will be adding a fix for it soon for sure.

**Comment by lautsevich** [comment]
We'll wait for it! Thx!

**Comment by SebastiaanKloos** [comment]
Pull request merged

**Comment by lautsevich** [comment]
Thx!
