### ISSUE TITLE
No fake data for theme Fruit

### ISSUE THREAD

**Issue by blackyzero** [oc-shopaholic/oc-fake-data-shopaholic-plugin#24]
Hello,

I am using theme Biolia E-Commerce, but there is no fake data for this them,

Is there any specific setting need?

```
php artisan shopaholic:generate.theme.fake.data

 Select theme [sneakers]:
  [0] sneakers
 > 

```

The first command to generate fake data is able to show "Fruit" theme.

Thank you.

**Comment by lautsevich** [comment]
Hi, @blackyzero!

There's no demo data for the Biolia theme except the products in the catalog. We plan to add it soon. Follow issue #17.
